//------------------------------------------------------------------------------
// <auto-generated>
//     Koden er generert av et verktøy.
//     Kjøretidsversjon:4.0.30319.34014
//
//     Endringer i denne filen kan føre til feil virkemåte, og vil gå tapt hvis
//     koden genereres på nytt.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace Arkitektum.kommit.ebyggesak.model {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/byggesak/1.0")]
    [System.Xml.Serialization.XmlRootAttribute("Aktivitet", Namespace="http://skjema.kxml.no/byggesak/1.0", IsNullable=false)]
    public partial class AktivitetType {
        
        private SjekkpunkttypeType typeSjekkField;
        
        private AktivitetsstatusType statusField;
        
        private string beskrivelseField;
        
        private System.Nullable<System.DateTime> fristField;
        
        private bool fristFieldSpecified;
        
        private string kommentarField;
        
        private string ansvarligField;
        
        private string dokumentkategoriField;
        
        private string referanseJournalpostField;
        
        private string referanseDokumentField;
        
        private LinkType[] _linksField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SjekkpunkttypeType typeSjekk {
            get {
                return this.typeSjekkField;
            }
            set {
                this.typeSjekkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AktivitetsstatusType status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> frist {
            get {
                return this.fristField;
            }
            set {
                this.fristField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fristSpecified {
            get {
                return this.fristFieldSpecified;
            }
            set {
                this.fristFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string kommentar {
            get {
                return this.kommentarField;
            }
            set {
                this.kommentarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ansvarlig {
            get {
                return this.ansvarligField;
            }
            set {
                this.ansvarligField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dokumentkategori {
            get {
                return this.dokumentkategoriField;
            }
            set {
                this.dokumentkategoriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string referanseJournalpost {
            get {
                return this.referanseJournalpostField;
            }
            set {
                this.referanseJournalpostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string referanseDokument {
            get {
                return this.referanseDokumentField;
            }
            set {
                this.referanseDokumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("_links", Namespace="http://www.kxml.no/rest/1.0", IsNullable=false)]
        public LinkType[] _links {
            get {
                return this._linksField;
            }
            set {
                this._linksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/byggesak/1.0")]
    [System.Xml.Serialization.XmlRootAttribute("Sjekkpunkttype", Namespace="http://skjema.kxml.no/byggesak/1.0", IsNullable=false)]
    public partial class SjekkpunkttypeType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    

    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/byggesak/1.0")]
    [System.Xml.Serialization.XmlRootAttribute("Aktivitetsstatus", Namespace="http://skjema.kxml.no/byggesak/1.0", IsNullable=false)]
    public partial class AktivitetsstatusType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/byggesak/1.0")]
    [System.Xml.Serialization.XmlRootAttribute("Byggesak", Namespace="http://skjema.kxml.no/byggesak/1.0", IsNullable=false)]
    public partial class ByggesakType {
        
        private string systemIdField;
        
        private SaksnummerType saksnummerField;
        
        private SaksnummerType[] referanseKlagesakerField;
        
        private SaksnummerType[] referanseAndreSakerField;
        
        private string tittelField;
        
        private string adresseField;
        
        private string posisjonField;
        
        private string bygningsnummerField;
        
        private LinkType[] _linksField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string systemId {
            get {
                return this.systemIdField;
            }
            set {
                this.systemIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SaksnummerType saksnummer {
            get {
                return this.saksnummerField;
            }
            set {
                this.saksnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("saksnummer", IsNullable=false)]
        public SaksnummerType[] referanseKlagesaker {
            get {
                return this.referanseKlagesakerField;
            }
            set {
                this.referanseKlagesakerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("saksnummer", IsNullable=false)]
        public SaksnummerType[] referanseAndreSaker {
            get {
                return this.referanseAndreSakerField;
            }
            set {
                this.referanseAndreSakerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tittel {
            get {
                return this.tittelField;
            }
            set {
                this.tittelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string adresse {
            get {
                return this.adresseField;
            }
            set {
                this.adresseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string posisjon {
            get {
                return this.posisjonField;
            }
            set {
                this.posisjonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string bygningsnummer {
            get {
                return this.bygningsnummerField;
            }
            set {
                this.bygningsnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("_links", Namespace="http://www.kxml.no/rest/1.0", IsNullable=false)]
        public LinkType[] _links {
            get {
                return this._linksField;
            }
            set {
                this._linksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/byggesak/1.0")]
    [System.Xml.Serialization.XmlRootAttribute("Saksnummer", Namespace="http://skjema.kxml.no/byggesak/1.0", IsNullable=false)]
    public partial class SaksnummerType {
        
        private string saksaarField;
        
        private string sakssekvensnummerField;
        
        private LinkType[] _linksField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string saksaar {
            get {
                return this.saksaarField;
            }
            set {
                this.saksaarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string sakssekvensnummer {
            get {
                return this.sakssekvensnummerField;
            }
            set {
                this.sakssekvensnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("_links", Namespace="http://www.kxml.no/rest/1.0", IsNullable=false)]
        public LinkType[] _links {
            get {
                return this._linksField;
            }
            set {
                this._linksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/byggesak/1.0")]
    [System.Xml.Serialization.XmlRootAttribute("Dispensasjon", Namespace="http://skjema.kxml.no/byggesak/1.0", IsNullable=false)]
    public partial class DispensasjonType {
        
        private string dispensasjonstypeField;
        
        private string beskrivelseField;
        
        private LinkType[] _linksField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dispensasjonstype {
            get {
                return this.dispensasjonstypeField;
            }
            set {
                this.dispensasjonstypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("_links", Namespace="http://www.kxml.no/rest/1.0", IsNullable=false)]
        public LinkType[] _links {
            get {
                return this._linksField;
            }
            set {
                this._linksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/byggesak/1.0")]
    [System.Xml.Serialization.XmlRootAttribute("Fase", Namespace="http://skjema.kxml.no/byggesak/1.0", IsNullable=false)]
    public partial class FaseType {
        
        private string fasenavnField;
        
        private LinkType[] _linksField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fasenavn {
            get {
                return this.fasenavnField;
            }
            set {
                this.fasenavnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("_links", Namespace="http://www.kxml.no/rest/1.0", IsNullable=false)]
        public LinkType[] _links {
            get {
                return this._linksField;
            }
            set {
                this._linksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/byggesak/1.0")]
    [System.Xml.Serialization.XmlRootAttribute("Gebyrlinje", Namespace="http://skjema.kxml.no/byggesak/1.0", IsNullable=false)]
    public partial class GebyrlinjeType {
        
        private string idField;
        
        private string artikkelnummerField;
        
        private string beskrivelseField;
        
        private System.Nullable<double> antallField;
        
        private string enhetField;
        
        private System.Nullable<double> prisField;
        
        private LinkType[] _linksField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string artikkelnummer {
            get {
                return this.artikkelnummerField;
            }
            set {
                this.artikkelnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> antall {
            get {
                return this.antallField;
            }
            set {
                this.antallField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string enhet {
            get {
                return this.enhetField;
            }
            set {
                this.enhetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<double> pris {
            get {
                return this.prisField;
            }
            set {
                this.prisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("_links", Namespace="http://www.kxml.no/rest/1.0", IsNullable=false)]
        public LinkType[] _links {
            get {
                return this._linksField;
            }
            set {
                this._linksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/byggesak/1.0")]
    [System.Xml.Serialization.XmlRootAttribute("Mangel", Namespace="http://skjema.kxml.no/byggesak/1.0", IsNullable=false)]
    public partial class MangelType {
        
        private MangeltypeType typeField;
        
        private string statusField;
        
        private LinkType[] _linksField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MangeltypeType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("_links", Namespace="http://www.kxml.no/rest/1.0", IsNullable=false)]
        public LinkType[] _links {
            get {
                return this._linksField;
            }
            set {
                this._linksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/byggesak/1.0")]
    [System.Xml.Serialization.XmlRootAttribute("Mangeltype", Namespace="http://skjema.kxml.no/byggesak/1.0", IsNullable=false)]
    public partial class MangeltypeType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/byggesak/1.0")]
    [System.Xml.Serialization.XmlRootAttribute("Milepel", Namespace="http://skjema.kxml.no/byggesak/1.0", IsNullable=false)]
    public partial class MilepelType {
        
        private string systemIdField;
        
        private string beskrivelseField;
        
        private MilepeltypeType kategoriField;
        
        private System.Nullable<System.DateTime> fristField;
        
        private bool fristFieldSpecified;
        
        private System.Nullable<System.DateTime> utfoertField;
        
        private bool utfoertFieldSpecified;
        
        private System.Nullable<bool> internField;
        
        private string referanseJournalpostField;
        
        private string referanseDokumentField;
        
        private LinkType[] _linksField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string systemId {
            get {
                return this.systemIdField;
            }
            set {
                this.systemIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public MilepeltypeType kategori {
            get {
                return this.kategoriField;
            }
            set {
                this.kategoriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> frist {
            get {
                return this.fristField;
            }
            set {
                this.fristField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fristSpecified {
            get {
                return this.fristFieldSpecified;
            }
            set {
                this.fristFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
        public System.Nullable<System.DateTime> utfoert {
            get {
                return this.utfoertField;
            }
            set {
                this.utfoertField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool utfoertSpecified {
            get {
                return this.utfoertFieldSpecified;
            }
            set {
                this.utfoertFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> intern {
            get {
                return this.internField;
            }
            set {
                this.internField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string referanseJournalpost {
            get {
                return this.referanseJournalpostField;
            }
            set {
                this.referanseJournalpostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string referanseDokument {
            get {
                return this.referanseDokumentField;
            }
            set {
                this.referanseDokumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("_links", Namespace="http://www.kxml.no/rest/1.0", IsNullable=false)]
        public LinkType[] _links {
            get {
                return this._linksField;
            }
            set {
                this._linksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/byggesak/1.0")]
    [System.Xml.Serialization.XmlRootAttribute("Milepeltype", Namespace="http://skjema.kxml.no/byggesak/1.0", IsNullable=false)]
    public partial class MilepeltypeType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/byggesak/1.0")]
    [System.Xml.Serialization.XmlRootAttribute("Prosess", Namespace="http://skjema.kxml.no/byggesak/1.0", IsNullable=false)]
    public partial class ProsessType {
        
        private string systemIdField;
        
        private ProsesskategoriType kategoriField;
        
        private string antallUkerFristField;
        
        private System.Nullable<bool> medDispensasjonField;
        
        private bool medDispensasjonFieldSpecified;
        
        private System.Nullable<bool> medReguleringsendringField;
        
        private bool medReguleringsendringFieldSpecified;
        
        private string prosesskoeField;
        
        private string prosessteamField;
        
        private string prosessansvarligField;
        
        private GebyrlinjeType[] gebyrunderlagField;
        
        private LinkType[] _linksField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string systemId {
            get {
                return this.systemIdField;
            }
            set {
                this.systemIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ProsesskategoriType kategori {
            get {
                return this.kategoriField;
            }
            set {
                this.kategoriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
        public string antallUkerFrist {
            get {
                return this.antallUkerFristField;
            }
            set {
                this.antallUkerFristField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> medDispensasjon {
            get {
                return this.medDispensasjonField;
            }
            set {
                this.medDispensasjonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool medDispensasjonSpecified {
            get {
                return this.medDispensasjonFieldSpecified;
            }
            set {
                this.medDispensasjonFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> medReguleringsendring {
            get {
                return this.medReguleringsendringField;
            }
            set {
                this.medReguleringsendringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool medReguleringsendringSpecified {
            get {
                return this.medReguleringsendringFieldSpecified;
            }
            set {
                this.medReguleringsendringFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string prosesskoe {
            get {
                return this.prosesskoeField;
            }
            set {
                this.prosesskoeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string prosessteam {
            get {
                return this.prosessteamField;
            }
            set {
                this.prosessteamField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string prosessansvarlig {
            get {
                return this.prosessansvarligField;
            }
            set {
                this.prosessansvarligField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("gebyrlinje", IsNullable=false)]
        public GebyrlinjeType[] gebyrunderlag {
            get {
                return this.gebyrunderlagField;
            }
            set {
                this.gebyrunderlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("_links", Namespace="http://www.kxml.no/rest/1.0", IsNullable=false)]
        public LinkType[] _links {
            get {
                return this._linksField;
            }
            set {
                this._linksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/byggesak/1.0")]
    [System.Xml.Serialization.XmlRootAttribute("Prosesskategori", Namespace="http://skjema.kxml.no/byggesak/1.0", IsNullable=false)]
    public partial class ProsesskategoriType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/byggesak/1.0")]
    [System.Xml.Serialization.XmlRootAttribute("Vedtak", Namespace="http://skjema.kxml.no/byggesak/1.0", IsNullable=false)]
    public partial class VedtakType {
        
        private string beskrivelseField;
        
        private System.Nullable<System.DateTime> vedtaksdatoField;
        
        private VedtakstypeType statusField;
        
        private string referanseVedtaksdokumentField;
        
        private string[] referanseUnderlagField;
        
        private DispensasjonType[] dispensasjonerField;
        
        private LinkType[] _linksField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> vedtaksdato {
            get {
                return this.vedtaksdatoField;
            }
            set {
                this.vedtaksdatoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public VedtakstypeType status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string referanseVedtaksdokument {
            get {
                return this.referanseVedtaksdokumentField;
            }
            set {
                this.referanseVedtaksdokumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("systemid", IsNullable=false)]
        public string[] referanseUnderlag {
            get {
                return this.referanseUnderlagField;
            }
            set {
                this.referanseUnderlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("dispensasjon", IsNullable=false)]
        public DispensasjonType[] dispensasjoner {
            get {
                return this.dispensasjonerField;
            }
            set {
                this.dispensasjonerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("_links", Namespace="http://www.kxml.no/rest/1.0", IsNullable=false)]
        public LinkType[] _links {
            get {
                return this._linksField;
            }
            set {
                this._linksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skjema.kxml.no/byggesak/1.0")]
    [System.Xml.Serialization.XmlRootAttribute("Vedtakstype", Namespace="http://skjema.kxml.no/byggesak/1.0", IsNullable=false)]
    public partial class VedtakstypeType {
        
        private string kodeField;
        
        private string beskrivelseField;
        
        /// <remarks/>
        public string kode {
            get {
                return this.kodeField;
            }
            set {
                this.kodeField = value;
            }
        }
        
        /// <remarks/>
        public string beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.kxml.no/rest/1.0")]
    [System.Xml.Serialization.XmlRootAttribute("LinkListe", Namespace="http://www.kxml.no/rest/1.0", IsNullable=false)]
    public partial class LinkListeType {
        
        private LinkType[] _linksField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("_links")]
        public LinkType[] _links {
            get {
                return this._linksField;
            }
            set {
                this._linksField = value;
            }
        }
    }
}
